spring:
  profiles:
    active: dev
  main:
    banner_mode: off
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: lakadmakatag@gmail.com
    password: clevertec
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.ssl.enable]": true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
  aop:
    auto: false
    proxy-target-class: false
application:
  database:
    seed-programmatically: false
